<a href="https://colab.research.google.com/github/Carmen-N/Transformacion-de-Datos-con-Pandas-y-NumPy/blob/master/Datos_con_Pandas_y_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np


El array es el principal objeto de la librería. 

Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos

In [ ]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Volvemos nuestra lista, un array

In [ ]:
arr = np.array(lista)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o **listas** agrupadas una encima de la otra, es como una tabla de Excel

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices

Los elementos **se empiezan a contar desde 0.**

In [ ]:
arr[0]

1

Index	0	1	2	3	4	5	6	7	8


0	1	2	3	4	5	6	7	8	9

Es posible operar directamente con los elementos.

In [ ]:
arr[0] + arr[5]

7

0	+	5
1		6

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [ ]:
matriz[0]


array([1, 2, 3])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Nota: El primer elemento selecciona las filas, el segundo elemento las columnas

In [ ]:
matriz[0, 2]

3

# Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5

In [ ]:
Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

Si no se ingresa el valor de inicio, se toma el inicio como la posición 0.

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

En cambio, si no se le da una posición final, se regresan todos los elementos hasta el final del array.

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

También se puede trabajar por pasos.

In [ ]:
arr[::3]

array([1, 4, 7])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [ ]:
arr[-1]

9

In [ ]:
arr[-3:]

array([7, 8, 9])

Para el caso de las matrices, sucede algo similar.
Para acceder a los valores entre filas.
1 2 3 4 5 6 7 8 9

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores entre filas y columnas.

In [ ]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

**Crea una matriz de 3 dimensiones y cuéntanos:**


¿Qué pudiste hacer?

¿Cómo hacer un Slicing de los datos?

Cómo crear y manipular un array de 3 dimensiones

Importamos Numpy

In [ ]:
import numpy as np

In [ ]:
dimension3 = [[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]]
dimension3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

Creamos nuestro array, una manera sencilla de entender cómo funciona es por los corchetes que tiene.

Es como poner varias matrices juntas.


[[1,2],[3,4]] <-- Primera matriz
[[5,6], [7,8]] <-- Segunda matriz
[[9,10], [11,12]] <-- Tercera matriz

Pasamos nuesta matriz por numpy

In [ ]:
dimension3 = np.array(dimension3)
dimension3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

Los ejes de 3 dimesiones son Z, Y, X. En ese orden los vamos a usar.

dimension3[Z,Y,X]


La Z representa la profundidad, en este caso los niveles que tenemos.


[ 1,  2],
[ 3,  4] ,       <-- posición 0 

   [ 5,  6],
    [ 7,  8],     <-- posición 1

   [ 9, 10],
    [11, 12]    <--posición 2

In [ ]:
dimension3[2]

array([[ 9, 10],
       [11, 12]])

In [ ]:
dimension3[2,1]

array([11, 12])

In [ ]:
dimension3[2,1,0]

11

# ¿Cómo hacer Slicing?

Es de la misma manera que en una matriz de 2 dimensiones, simplemente le ponemos un paramétro más

In [ ]:
dimension3[:2,::,1: ]

array([[[2],
        [4]],

       [[6],
        [8]]])

Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

Podemos conocer el tipo de datos del array consultando la propiedad .dtype

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

Ahora vemos que los valores están con punto decimal.

In [ ]:
arr

array([1, 2, 3, 4])

Si ya se tiene el array definido, se utiliza el método **.astype()** para convertir el tipo de dato.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

También podemos convertir los datos en tipo **string.**

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

De igual manera, se puede pasar de string a número.

In [ ]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

Si un elemento **no es de tipo número**, el método** falla**

In [ ]:
arr = np.array(['hola','0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored

**Dimensiones**

scalar: dim = 0 Un solo dato o valor

vector: dim = 1 Listas de Python

matriz: dim = 2 Hoja de cálculo

tensor: dim > 3 Series de tiempo o Imágenes

Declarando un escalar.

In [ ]:
scalar = np.array(42)
print(scalar) 
scalar.ndim 

42


0

Declarando un vector.

In [ ]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim 

[1 2 3]


1

Declarando una matriz.

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

Declarando un tensor.

In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

**Agregar o eliminar dimensiones**

Se puede definir el número de dimensiones desde la declaración del array

In [ ]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 

[[[[[[[[[[1 2 3]]]]]]]]]]


In [ ]:
vector.ndim

10

Se pueden expandir dimensiones a los array ya existentes.

Axis = 0 hace refencia a las filas, mientras que axis = 1 a las columnas.

In [ ]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand) 
expand.ndim 

[[1 2 3]]


2

Remover/comprimir las dimensiones que no están siendo usadas.

In [ ]:
print(vector, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10


In [ ]:
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[1 2 3] 1


**Reto**

Definir un tensor de 5 dimensiones

Sumar una dimensión en algún eje

Borrar dimensiones que no se usen

In [ ]:
tensor5 = np.array([[[[1, 2],[3, 4]], [[5, 6],[7, 8]]], [[[1, 2],[3, 4]], [[5, 6],[7, 8]]]], ndmin = 5)
print(tensor5, tensor5.ndim)

[[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]] 5


In [ ]:
expand5 = np.expand_dims(tensor5, axis=1)
print(expand5, expand5.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6


In [ ]:
import pandas as pd 
import numpy as np

# Creando arrays

In [ ]:
import numpy as np

Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

Este método de NumPy nos permite generar arrays sin definir previamente una lista.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



Un tercer argumento permite definir un tamaño de paso.

In [ ]:
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**np.zeros()** Nos permite definir estructuras o esquemas.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

De igual manera, tenemos **np.ones()**

In [ ]:
np.ones(3)


array([1., 1., 1.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

**np.linspace()** 
Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

In [ ]:
np.linspace(0, 10 , 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

También podemos crear una matriz con una diagonal de 1 y el resto de 9.

In [ ]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Otro método importante es generar números aleatorios.

In [ ]:
np.random.rand()

0.4784172931156526

También se pueden generar vectores.

In [ ]:
np.random.rand(4)

array([3.48879445e-01, 8.63899526e-04, 9.02227252e-01, 3.34752874e-01])

Y a su vez generar matrices.

In [ ]:
np.random.rand(4,4)

array([[0.32274312, 0.41038136, 0.76660458, 0.47763909],
       [0.98634358, 0.92929017, 0.98640785, 0.55242588],
       [0.90985033, 0.24180353, 0.78990099, 0.50924192],
       [0.61815887, 0.69792043, 0.81378397, 0.83764379]])

NumPy nos permite también generar números enteros.
En este caso números enteros entre el 1 y 14

In [ ]:
np.random.randint(1,15)

10

In [ ]:
np.random.randint(1,12)

1

También podemos llevarlos a una estructura definida.

In [ ]:
np.random.randint(1,15, (3,3))

array([[ 5,  7, 11],
       [13,  6, 11],
       [ 8,  5,  3]])

Existen diferentes operaciones que se pueden usar para los arrays de NumPy.

In [ ]:
lista =[1,2]
lista

[1, 2]

Una lista de Python entiende que quieres duplicar los datos. No es lo que buscamos.

In [ ]:
lista * 2


[1, 2, 1, 2]

Pero Numpy lo entiende mucho mejor

In [ ]:
arr =np.arange(0,10)
arr2 =arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora multiplicamos por un vector:

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

División con un vector
Como en este caso la primera posición del array es 0, muestra un error pero, no detiene el proceso.

In [ ]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Elevar a un vector:

In [ ]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Sumar dos arrays de igual dimensiones las hace elemento por elemento:

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Lo mismo aplica para matrices.

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz-matriz

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Una operación importante es la de punto por punto, aquí dos formas de hacerla:

In [ ]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

**Pandas**

Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos. El nombre viene de “Panel data”.

•Velocidad

• Poco código

• Múltiples formatos de archivos

• Alineación inteligente





**Pandas Series**

Es muy parecido a un array de una dimensión (o vector) de NumPy.

• Arreglo unidimensional indexado

• Búsqueda por índice

• Slicing

• Operaciones aritméticas


• Distintos tipos de datos


**Pandas DataFrame**

Muy parecido a las estructuras matriciales trabajadas con NumPy.

• Estructura principal

• Arreglo de dos dimensiones

• Búsqueda por índice (columnas o filas)

• Slicing

• Operaciones aritméticas

• Distintos tipos de datos

• Tamaño variable


**Series**

Es un arreglo unidimensional indexado

In [ ]:
import pandas as pd

Definiendo una lista con índices específicos

In [ ]:
psg_players = pd.Series(['Navas','Mbappe','Neymar','Messi'], index=[1,7,10,30])

psg_players 

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

Búsqueda por índices

In [ ]:
dict = {1: 'Navas', 7: 'Mbappe', 10: 'Neymar', 30:'Messi'}
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
psg_players[7]

'Mbappe'

Búsqueda mediante Slicing

In [ ]:
psg_players[0:3]

1      Navas
7     Mbappe
10    Neymar
dtype: object

**Pandas**

Similar a la estructura matricial

In [ ]:
dict = {'Jugador':['Navas','Mbappe','Neymar','Messi'],
 'Altura':[183.0, 170.0, 170.0, 163.0],
  'Goles':[2, 200, 150, 500]}
df_players = pd.DataFrame(dict, index=[1,7,10,30])
df_players

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    150
30   Messi   163.0    500

ejemplo 

In [ ]:
dict = {'Marca':['Mazda','Chevrolet','Renault','Toyota','Suzuki'],
'Nombre':['Mazda 2','Onix','kwid','Corolla Cross','Jimmy'],
'Tipo':['Hatchback','Sedan','Mini Suv','Suv','Todo Terreno'],
'combustible':['Coriente','Extra','Extra','Extra','Corriente'],
'Precio':[75000000, 80000000, 52000000, 119000000,99000000]}
pd.DataFrame(dict, index=[4, 7, 41, 50, 89])

Marca         Nombre          Tipo combustible     Precio
4       Mazda        Mazda 2     Hatchback    Coriente   75000000
7   Chevrolet           Onix         Sedan       Extra   80000000
41    Renault           kwid      Mini Suv       Extra   52000000
50     Toyota  Corolla Cross           Suv       Extra  119000000
89     Suzuki          Jimmy  Todo Terreno   Corriente   99000000

ejemplo 

In [ ]:
granada_fc = {'Jugador':['Luis Suarez','Jorge Molina', 'Antonio Puertas', 'German Sanchez', 'Luis Milla', 'Luis Manuel Arantes Maximiano'],
 'Posicion':['Delantero', 'Delantero', 'Centrocampista', 'Defensa', 'Centrocampista', 'Portero'],
 'Altura':[185.0, 187.0, 185.0, 187.0, 175.0, 190.0],
 'Goles':[7, 7, 5, 2, 2, 0]}
df_granada_players = pd.DataFrame(granada_fc, index=[9, 23, 10, 6, 5, 1])
df_granada_players



Jugador        Posicion  Altura  Goles
9                     Luis Suarez       Delantero   185.0      7
23                   Jorge Molina       Delantero   187.0      7
10                Antonio Puertas  Centrocampista   185.0      5
6                  German Sanchez         Defensa   187.0      2
5                      Luis Milla  Centrocampista   175.0      2
1   Luis Manuel Arantes Maximiano         Portero   190.0      0

Búsqueda por índices. **Columnas**

In [ ]:
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

Búsqueda por **índice.**

In [ ]:
df_players.index

Int64Index([1, 7, 10, 30], dtype='int64')

# Los datos nulos son dolores de cabeza para este mundo de la ciencia de datos y se van a encontrar mucho en nuestros DataFrames

Creamos un DataFrame con algunos valores nulos

In [78]:
import pandas as pd
import numpy as np

dict = {'Col1':[1,2,3,np.nan],
'Col2':[4, np.nan,6,7],
'Col3':['a','b','c', None]}

In [80]:
df = pd.DataFrame(dict)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

**Identificar valores nulos en un DataFrame**

In [81]:
df.isnull()

Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

**Identificar valores nulos con un valor numérico**

In [82]:
df.isnull()*1

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

Sustituir los valores nulos **por una cadena**

In [83]:
df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

Sustituir valores nulos por una medida estadística realizada con los valores de las columnas

In [84]:
df.fillna(df.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

**Sustituir valores nulos por valores de interpolación**

In [85]:
df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

**Eliminar** valores nulos

In [86]:
df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

# Combinando DataFrames

Existen diferentes formas de fusionar dos DataFrames. Esto se hace a través de la lógica de combinación como se muestra a continuación:

*Left join:* Da prioridad al DataFrame de la izquierda. Trae siempre los datos de la izquierda y las filas en común con el DataFrame de la derecha.

*Right join:* Da prioridad al DataFrame de la derecha. Trae siempre los datos de la derecha y las filas en común con el DataFrame de la izquierda.

*Inner join:* Trae solamente aquellos datos que son común en ambos DataFrame

*Outer join:* Trae los datos tanto del DataFrame de la izquierda como el de la derecha, incluyendo los datos que comparten ambos.

# Merge y Concat

Como podemos usar la lógica anteriormente vista en código, usando los parámetros de Pandas

Importamos Pandas y Numpy

In [88]:
import pandas as pd
import numpy as np

# Concat

vamos a crear un DataFrame nuevo

In [89]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2','A3'],
        'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']})


df2 = pd.DataFrame({'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']})

**Concatenar** los DataFrames

In [90]:
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

**Corregir** los índices

In [91]:
pd.concat([df1,df2], ignore_index= True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

Por **axis 1**

In [92]:
pd.concat([df1,df2], axis = 1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

# Merge

Creamos DataFrame


In [93]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

Unir el DataFrame*** Der a Izq***

In [94]:
izq.merge(der)

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

# MERGE 2

In [96]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

Hay diferencias entre algunas columnas, por esa razón hay que separarlos de esta manera:

In [97]:
izq.merge(der, left_on = 'key', right_on='key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2
3  k3  A3  B3    k3  C3  D3

# MERGE 3

In [98]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2',np.nan],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

Si tenemos un NaNen nuestro DataFrame, pandas no lo detectará como un mach. Se soluciona con How, dando así, una preferencia.

In [99]:
izq.merge(der, left_on = 'key', right_on='key_2', how='left')                               

key   A   B key_2    C    D
0  k0  A0  B0    k0   C0   D0
1  k1  A1  B1    k1   C1   D1
2  k2  A2  B2    k2   C2   D2
3  k3  A3  B3   NaN  NaN  NaN

# Join

**Join** Es otra herramienta para hacer exactamente lo mismo, una combinación. La diferencia es que join va a ir a los índices y no a columnas específicas.

In [100]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']},
  index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']},
  index=['k0','k2','k3'])

Combinamos izq con der

In [101]:
izq.join(der)

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

Traer todos los datos aunque no hagan match.

In [102]:
izq.join(der, how = 'outer')

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

# Pregunta:
En temas de performance y velocidad, ¿cuál es mejor el Merge o el Join, cuando se trata de miles de registros?

# Respuesta:
join suele ser mejor