<a href="https://colab.research.google.com/github/Carmen-N/Transformacion-de-Datos-con-Pandas-y-NumPy/blob/master/Datos_con_Pandas_y_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd 
import numpy as np


El array es el principal objeto de la librería. 

Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos

In [ ]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Volvemos nuestra lista, un array

In [ ]:
arr = np.array(lista)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o **listas** agrupadas una encima de la otra, es como una tabla de Excel

In [ ]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices

Los elementos **se empiezan a contar desde 0.**

In [ ]:
arr[0]

1

Index	0	1	2	3	4	5	6	7	8


0	1	2	3	4	5	6	7	8	9

Es posible operar directamente con los elementos.

In [ ]:
arr[0] + arr[5]

7

0	+	5
1		6

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [ ]:
matriz[0]


array([1, 2, 3])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Nota: El primer elemento selecciona las filas, el segundo elemento las columnas

In [ ]:
matriz[0, 2]

3

# Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5

In [ ]:
Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

Si no se ingresa el valor de inicio, se toma el inicio como la posición 0.

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

En cambio, si no se le da una posición final, se regresan todos los elementos hasta el final del array.

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

También se puede trabajar por pasos.

In [ ]:
arr[::3]

array([1, 4, 7])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [ ]:
arr[-1]

9

In [ ]:
arr[-3:]

array([7, 8, 9])

Para el caso de las matrices, sucede algo similar.
Para acceder a los valores entre filas.
1 2 3 4 5 6 7 8 9

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores entre filas y columnas.

In [ ]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

**Crea una matriz de 3 dimensiones y cuéntanos:**


¿Qué pudiste hacer?

¿Cómo hacer un Slicing de los datos?

Cómo crear y manipular un array de 3 dimensiones

Importamos Numpy

In [ ]:
import numpy as np

In [ ]:
dimension3 = [[[1,2],[3,4]], [[5,6], [7,8]], [[9,10], [11,12]]]
dimension3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

Creamos nuestro array, una manera sencilla de entender cómo funciona es por los corchetes que tiene.

Es como poner varias matrices juntas.


[[1,2],[3,4]] <-- Primera matriz
[[5,6], [7,8]] <-- Segunda matriz
[[9,10], [11,12]] <-- Tercera matriz

Pasamos nuesta matriz por numpy

In [ ]:
dimension3 = np.array(dimension3)
dimension3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

Los ejes de 3 dimesiones son Z, Y, X. En ese orden los vamos a usar.

dimension3[Z,Y,X]


La Z representa la profundidad, en este caso los niveles que tenemos.


[ 1,  2],
[ 3,  4] ,       <-- posición 0 

   [ 5,  6],
    [ 7,  8],     <-- posición 1

   [ 9, 10],
    [11, 12]    <--posición 2

In [ ]:
dimension3[2]

array([[ 9, 10],
       [11, 12]])

In [ ]:
dimension3[2,1]

array([11, 12])

In [ ]:
dimension3[2,1,0]

11

# ¿Cómo hacer Slicing?

Es de la misma manera que en una matriz de 2 dimensiones, simplemente le ponemos un paramétro más

In [ ]:
dimension3[:2,::,1: ]

array([[[2],
        [4]],

       [[6],
        [8]]])

Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

Podemos conocer el tipo de datos del array consultando la propiedad .dtype

In [ ]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

Ahora vemos que los valores están con punto decimal.

In [ ]:
arr

array([1, 2, 3, 4])

Si ya se tiene el array definido, se utiliza el método **.astype()** para convertir el tipo de dato.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

También podemos convertir los datos en tipo **string.**

In [ ]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

De igual manera, se puede pasar de string a número.

In [ ]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

Si un elemento **no es de tipo número**, el método** falla**

In [ ]:
arr = np.array(['hola','0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored

**Dimensiones**

scalar: dim = 0 Un solo dato o valor

vector: dim = 1 Listas de Python

matriz: dim = 2 Hoja de cálculo

tensor: dim > 3 Series de tiempo o Imágenes

Declarando un escalar.

In [ ]:
scalar = np.array(42)
print(scalar) 
scalar.ndim 

42


0

Declarando un vector.

In [ ]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim 

[1 2 3]


1

Declarando una matriz.

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

Declarando un tensor.

In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

**Agregar o eliminar dimensiones**

Se puede definir el número de dimensiones desde la declaración del array

In [ ]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 

[[[[[[[[[[1 2 3]]]]]]]]]]


In [ ]:
vector.ndim

10

Se pueden expandir dimensiones a los array ya existentes.

Axis = 0 hace refencia a las filas, mientras que axis = 1 a las columnas.

In [ ]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand) 
expand.ndim 

[[1 2 3]]


2

Remover/comprimir las dimensiones que no están siendo usadas.

In [ ]:
print(vector, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10


In [ ]:
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[1 2 3] 1


**Reto**

Definir un tensor de 5 dimensiones

Sumar una dimensión en algún eje

Borrar dimensiones que no se usen

In [ ]:
tensor5 = np.array([[[[1, 2],[3, 4]], [[5, 6],[7, 8]]], [[[1, 2],[3, 4]], [[5, 6],[7, 8]]]], ndmin = 5)
print(tensor5, tensor5.ndim)

[[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]] 5


In [ ]:
expand5 = np.expand_dims(tensor5, axis=1)
print(expand5, expand5.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6


In [16]:
import pandas as pd 
import numpy as np

# Creando arrays

In [20]:
import numpy as np

Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

Este método de NumPy nos permite generar arrays sin definir previamente una lista.

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



Un tercer argumento permite definir un tamaño de paso.

In [21]:
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**np.zeros()** Nos permite definir estructuras o esquemas.

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

De igual manera, tenemos **np.ones()**

In [26]:
np.ones(3)


array([1., 1., 1.])

In [27]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

**np.linspace()** 
Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

In [28]:
np.linspace(0, 10 , 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

También podemos crear una matriz con una diagonal de 1 y el resto de 9.

In [29]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Otro método importante es generar números aleatorios.

In [30]:
np.random.rand()

0.4784172931156526

También se pueden generar vectores.

In [31]:
np.random.rand(4)

array([3.48879445e-01, 8.63899526e-04, 9.02227252e-01, 3.34752874e-01])

Y a su vez generar matrices.

In [32]:
np.random.rand(4,4)

array([[0.32274312, 0.41038136, 0.76660458, 0.47763909],
       [0.98634358, 0.92929017, 0.98640785, 0.55242588],
       [0.90985033, 0.24180353, 0.78990099, 0.50924192],
       [0.61815887, 0.69792043, 0.81378397, 0.83764379]])

NumPy nos permite también generar números enteros.
En este caso números enteros entre el 1 y 14

In [33]:
np.random.randint(1,15)

10

In [34]:
np.random.randint(1,12)

1

También podemos llevarlos a una estructura definida.

In [35]:
np.random.randint(1,15, (3,3))

array([[ 5,  7, 11],
       [13,  6, 11],
       [ 8,  5,  3]])

Existen diferentes operaciones que se pueden usar para los arrays de NumPy.

In [37]:
lista =[1,2]
lista

[1, 2]

Una lista de Python entiende que quieres duplicar los datos. No es lo que buscamos.

In [38]:
lista * 2


[1, 2, 1, 2]

Pero Numpy lo entiende mucho mejor

In [40]:
arr =np.arange(0,10)
arr2 =arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora multiplicamos por un vector:

In [41]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

División con un vector
Como en este caso la primera posición del array es 0, muestra un error pero, no detiene el proceso.

In [42]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Elevar a un vector:

In [43]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Sumar dos arrays de igual dimensiones las hace elemento por elemento:

In [44]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Lo mismo aplica para matrices.

In [46]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz-matriz

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Una operación importante es la de punto por punto, aquí dos formas de hacerla:

In [48]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [49]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

**Pandas**

Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos. El nombre viene de “Panel data”.

•Velocidad

• Poco código

• Múltiples formatos de archivos

• Alineación inteligente





**Pandas Series**

Es muy parecido a un array de una dimensión (o vector) de NumPy.

• Arreglo unidimensional indexado

• Búsqueda por índice

• Slicing

• Operaciones aritméticas


• Distintos tipos de datos


**Pandas DataFrame**

Muy parecido a las estructuras matriciales trabajadas con NumPy.

• Estructura principal

• Arreglo de dos dimensiones

• Búsqueda por índice (columnas o filas)

• Slicing

• Operaciones aritméticas

• Distintos tipos de datos

• Tamaño variable


**Series**

Es un arreglo unidimensional indexado

In [50]:
import pandas as pd