<a href="https://colab.research.google.com/github/Carmen-N/proyectoDemoCursoPrework/blob/master/Datos_con_Pandas_y_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd 
import numpy as np


El array es el principal objeto de la librería. 

Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos

In [2]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Volvemos nuestra lista, un array

In [18]:
arr = np.array(lista)
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o **listas** agrupadas una encima de la otra, es como una tabla de Excel

In [17]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices

Los elementos **se empiezan a contar desde 0.**

In [19]:
arr[0]

1

Index	0	1	2	3	4	5	6	7	8


0	1	2	3	4	5	6	7	8	9

Es posible operar directamente con los elementos.

In [20]:
arr[0] + arr[5]

7

0	+	5
1		6

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [24]:
matriz[0]


array([1, 2, 3])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Nota: El primer elemento selecciona las filas, el segundo elemento las columnas

In [25]:
matriz[0, 2]

3

# Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5

In [ ]:
Slicing
Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5

In [26]:
arr[1:6]

array([2, 3, 4, 5, 6])

Si no se ingresa el valor de inicio, se toma el inicio como la posición 0.

In [27]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

En cambio, si no se le da una posición final, se regresan todos los elementos hasta el final del array.

In [28]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

También se puede trabajar por pasos.

In [29]:
arr[::3]

array([1, 4, 7])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [30]:
arr[-1]

9

In [31]:
arr[-3:]

array([7, 8, 9])

Para el caso de las matrices, sucede algo similar.
Para acceder a los valores entre filas.
1 2 3 4 5 6 7 8 9

In [32]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores entre filas y columnas.

In [33]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

**Crea una matriz de 3 dimensiones y cuéntanos:**


¿Qué pudiste hacer?

¿Cómo hacer un Slicing de los datos?